src/app/__init__.py
from flask import Flask, render_template
from .projects import project_bp
import webview

PORT = 5003

app = Flask(__name__)

app.register_blueprint(project_bp, url_prefix='/projects')

window = webview.create_window('Mivisor Novo', f'http://localhost:{PORT}')


@app.route('/')
def hello_world():
    print('hello, from Flask')
    return render_template('index.html')


def start_server():
    app.run(port=PORT)

src/app/projects/__init__.py
from flask import Blueprint

project_bp = Blueprint('project', __name__)

from . import views

src/app/projects/views.py
import os
import datetime as dt
from flask import request, redirect, render_template, url_for, jsonify
from . import project_bp as project

PROJECT_DIR = os.path.join(os.getcwd(), 'projects')

@project.route('/api/new')
def create_project():
    proj_name = request.args.get('name')
    if not proj_name:
        return jsonify(success=False, message='No project name specified.')
    proj_dir = os.path.join('projects', proj_name)
    proj_dir = os.path.join(os.getcwd(), proj_dir)
    if os.path.exists(proj_dir):
        return jsonify(success=False, message='Project already exists.')
    else:
        os.makedirs(proj_dir)
        return jsonify(success=True)


@project.route('/api/project/<name>')
def load_project(name):
    project_data = {
        'name': name
    }
    return jsonify(project_data)


@project.route('/')
def list_projects():
    dirs = []
    for d in os.listdir(PROJECT_DIR):
        creation_datetime = os.stat(os.path.join(PROJECT_DIR, d)).st_ctime
        creation_datetime = dt.datetime.fromtimestamp(creation_datetime).strftime('%d/%m/%Y %H:%M:%S')
        dirs.append((d, creation_datetime))
    return render_template('projects/list.html', projects=dirs)


@project.route('/project/<name>')
def display_project(name):
    return render_template('projects/main.html',
                           project_url=url_for('project.load_project', name=name))

src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/materialdesignicons.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/buefy.min.css') }}">
    {% endblock %}
</head>
<body>
{% block page_content %}
{% endblock %}
</body>
{% block scripts %}
<script src="{{ url_for('static', filename='js/axios.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/vue.js') }}"></script>
<script src="{{ url_for('static', filename='js/buefy.min.js') }}"></script>
{% endblock %}
</html>

src/app/templates/index.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock %}

{% block page_content %}
<section id="app" class="section">
    <div class="columns">
        <div class="column is-2">
            {% include "menu.html" %}
        </div>
        <div class="column">
            <div class="container">
                <div class="columns">
                    <div class="column">
                        <nav class="panel">
                            <p class="panel-heading">
                                Projects
                            </p>
                            <a class="panel-block" @click="prompt">
                                <span class="panel-icon">
                                    <i class="mdi mdi-folder-plus-outline mdi-18px" aria-hidden="true"></i>
                                </span>
                                <b-tooltip label="สร้างโปรเจคใหม่" type="is-light is-info">
                                    New project
                                </b-tooltip>
                            </a>
                            <a class="panel-block" href="{{ url_for('project.list_projects') }}">
                                <span class="panel-icon">
                                    <i class="mdi mdi-folder-open-outline mdi-18px" aria-hidden="true"></i>
                                </span>
                                <b-tooltip label="เปิดโปรเจคที่สร้างไว้" type="is-light is-info">
                                    Open existing project
                                </b-tooltip>
                            </a>
                            <a class="panel-block">
                                <span class="panel-icon">
                                    <i class="mdi mdi-close-thick mdi-18px" aria-hidden="true"></i>
                                </span>
                                <b-tooltip label="ออกจากโปรแกรม" type="is-light is-info">
                                    Exit
                                </b-tooltip>
                            </a>
                        </nav>
                    </div>
                </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    new Vue({
        el: '#app',
        data() {
            return {
            }
        },
        methods: {
            prompt() {
                let self = this
                this.$buefy.dialog.prompt({
                    message: 'What is your project name?',
                    inputAttrs: {
                        placeholder: 'e.g. My Project',
                    },
                    trapFocus: true,
                    onConfirm: function(value) {
                        axios.get("/projects/api/new", { params: { name: value }
                        }).then((resp)=>{
                            console.log(resp)
                            if(resp.data.success) {
                                self.$buefy.toast.open({
                                    message: "New project folder has been created.",
                                    type: 'is-success'
                                })
                                window.location = '/projects'
                            } else {
                                self.$buefy.toast.open({
                                    message: resp.data.message,
                                    type: 'is-danger'
                                })
                            }
                        })
                    }
                })
            }
        }
    })
</script>
{% endblock %}

src/app/templates/menu.html
<b-menu>
    <b-menu-list label="Menu">
        <b-menu-item icon="information-outline" label="Info"></b-menu-item>
        <b-menu-item icon="settings">
        <template slot="label" slot-scope="props">
            Projects
        </template>
        <b-menu-item icon="format-list-bulleted-square" label="All"></b-menu-item>
        <b-menu-item icon="database">
            <template slot="label">
            Databases
            <b-dropdown aria-role="list" class="is-pulled-right" position="is-bottom-left">
                <b-icon icon="dots-vertical" slot="trigger"></b-icon>
                <b-dropdown-item aria-role="listitem">Action</b-dropdown-item>
                <b-dropdown-item aria-role="listitem">Another action</b-dropdown-item>
                <b-dropdown-item aria-role="listitem">Something else</b-dropdown-item>
            </b-dropdown>
            </template>
        </b-menu-item>
        <b-menu-item icon="cash-multiple" label="Payments" disabled></b-menu-item>
        </b-menu-item>
        <b-menu-item icon="account" label="My Account">
        <b-menu-item label="Account data"></b-menu-item>
        <b-menu-item label="Addresses"></b-menu-item>
        </b-menu-item>
    </b-menu-list>
    <b-menu-list>
        <b-menu-item label="Utilities" icon="tools">
            <b-menu-item icon="magnify" label="Quick scan"></b-menu-item>
            <b-menu-item icon="check-decagram" label="Sanity check"></b-menu-item>
        </b-menu-item>
    </b-menu-list>
    <b-menu-list label="Actions">
        <b-menu-item label="Logout"></b-menu-item>
    </b-menu-list>
</b-menu>

src/app/templates/projects/list.html
{% extends "base.html" %}

{% block page_content %}
<section id="app" class="section">
    <div class="columns">
        <div class="column is-2">
            {% include "menu.html" %}
        </div>
        <div class="column">
            <h1 class="title">All Projects</h1>
            <div class="box">
                <table class="table is-striped is-fullwidth">
                    <thead>
                    <th>No.</th>
                    <th>Name</th>
                    <th>Created At</th>
                    <th></th>
                    </thead>
                    {% for proj,ctime in projects %}
                    <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ proj }}</td>
                            <td>{{ ctime }}</td>
                            <td>
                                <a href="{{ url_for('project.display_project', name=proj) }}">
                                    <span>View</span>
                                    <span class="icon">
                                        <i class="mdi mdi-chevron-right"></i>
                                    </span>
                                </a>
                            </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    new Vue({
        el: '#app',
        data() {
            return {}
        },
    })
</script>
{% endblock %}

src/app/templates/projects/main.html
{% extends "base.html" %}

{% block page_content %}
<section id="app" class="section">
    <div class="columns">
        <div class="column is-2">
            {% include "menu.html" %}
        </div>
        <div class="column">
            <h1 class="title"><% projectData.name %></h1>
            <div class="box">
                <b-tabs type="is-boxed">
                    <b-tab-item label="Data">
                        <table class="table is-striped">
                            <tr>
                                <td class="label">Data Source</td>
                                <td>
                                </td>
                            </tr>
                        </table>
                    </b-tab-item>
                    <b-tab-item label="Info">
                        <table class="table is-striped">
                            <tr>
                                <td class="label">Name</td>
                                <td><% projectData.name %></td>
                            </tr>
                        </table>
                    </b-tab-item>
                    <b-tab-item label="Settings"></b-tab-item>
                </b-tabs>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    new Vue({
        el: '#app',
        delimiters: ['<%', '%>'],
        data() {
            return {
                projectUrl: {{ project_url|tojson|safe }},
                projectData: null
            }
        },
        methods: {
            loadData() {
                let self = this
                axios.get(this.projectUrl).then((resp)=>{
                    console.log(resp)
                    self.projectData = resp.data
                })
            }
        },
        mounted() {
            this.loadData()
        }
    })
</script>
{% endblock %}